{% set version = "0.6.3" %}

package:
  name: jaws
  version: {{ version }}

source:
  url: https://github.com/jaws/jaws/archive/{{ version }}.tar.gz
  sha256: 4b032aeeee195cfee124e6f993e5c00acea82fbfcc6c7bcd8fd9208931a9dec8

build:
  #noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pandas
    - scipy
  run:
    - python
    - pandas
    - numpy >=1.12
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - netcdf4
    - scipy
    - requests

test:
  imports:
    - jaws
    - jaws.aaws2nc
    - jaws.gcnet2nc
    - jaws.imau2nc
    - jaws.promice2nc

about:
  home: https://github.com/jaws/jaws
  license: Apache, Version 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Justify idiosyncratic ASCII AWS formats into analyzable netCDF formats.'

extra:
  recipe-maintainers:
    - ajcse1
    - czender
