{% set version = "0.8.1" %}

package:
  name: jaws
  version: {{ version }}

source:
  url: https://github.com/jaws/jaws/archive/{{ version }}.tar.gz
  sha256: 65ef5fcea43c5e305108a84780a23db43b1bb9c46e0728f6363fa7f80df33b88

build:
  number: 0
  # script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - pandas
    - scipy
    - numpy >=1.15.2
    - requests
    - xarray
  run:
    - python
    - pandas
    - numpy >=1.15.2
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - netcdf4
    - scipy
    - requests

test:
  imports:
    - jaws
    - jaws.aaws2nc
    - jaws.gcnet2nc
    - jaws.imau2nc
    - jaws.promice2nc

about:
  home: https://github.com/jaws/jaws
  license: Apache, Version 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Justify idiosyncratic ASCII AWS formats into analyzable netCDF formats.'

extra:
  recipe-maintainers:
    - ajcse1
    - czender
