{% set version = "1.0" %}

package:
  name: jaws
  version: {{ version }}

source:
  url: https://github.com/jaws/jaws/archive/{{ version }}.tar.gz
  sha256: 6a3c091e70a8286805eaa4c1111586d6649ad3004d9d0ca2c56d0200fa6b973a

build:
  number: 0
  # script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - pandas
    - scipy
    - numpy >=1.15.2
    - requests
    - xarray
    - metpy >=0.10.0
  run:
    - python
    - pandas
    - numpy >=1.15.2
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - netcdf4
    - scipy
    - requests
    - metpy >=0.10.0

test:
  imports:
    - jaws
    - jaws.aaws2nc
    - jaws.gcnet2nc
    - jaws.imau2nc
    - jaws.promice2nc

about:
  home: https://github.com/jaws/jaws
  license: Apache, Version 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Justify idiosyncratic ASCII AWS formats into analyzable netCDF formats.'

extra:
  recipe-maintainers:
    - ajcse1
    - czender
