{% set version = "0.5.2" %}

package:
  name: jaws
  version: {{ version }}

source:
  url: https://github.com/jaws/jaws/archive/{{ version }}.tar.gz
  sha256: eef6473b254dda5eb0a0442bf54c7261f72af6016209437948f58143df3098af

build:
  #noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pandas
  run:
    - python
    - pandas
    - numpy >=1.12
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - netcdf4

test:
  imports:
    - jaws
    - jaws.aaws2nc
    - jaws.gcnet2nc
    - jaws.imau2nc
    - jaws.promice2nc

about:
  home: https://github.com/jaws/jaws
  license: Apache, Version 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Justify idiosyncratic ASCII AWS formats into analyzable netCDF formats.'

extra:
  recipe-maintainers:
    - ajcse1
    - czender
