{% set version = "1.0" %}

package:
  name: jaws
  version: {{ version }}

source:
  url: https://github.com/jaws/jaws/archive/{{ version }}.tar.gz
  sha256: 172f216d1559f9f02619eee28a9fea6cb63f0d18678e98e757951cd85f4c8c34

build:
  number: 3
  noarch: python
  entry_points:
    - jaws = jaws.jaws:start
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    # imports itself at install time so we need all deps here
    - pandas
    - numpy >=1.15.2
    - xarray
    - pytz
    - netcdf4
    - matplotlib-base
    - netcdf4
    - scipy
    - requests
    - metpy >=0.10.0
  run:
    - python >=3.6
    - pandas
    - numpy >=1.15.2
    - xarray
    - pytz
    - netcdf4
    - matplotlib-base
    - netcdf4
    - scipy
    - requests
    - metpy >=0.10.0

test:
  imports:
    - jaws
    - jaws.aaws2nc
    - jaws.gcnet2nc
    - jaws.imau2nc
    - jaws.promice2nc
  commands:
    - jaws -h
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaws/jaws
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Justify idiosyncratic ASCII AWS formats into analyzable netCDF formats.'

extra:
  recipe-maintainers:
    - ajcse1
    - czender
