appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tdLFhmk41/poSpZbXSm8pzY5ffKnN7YgNjrOLpJxEDrlzoqblgKEOiL6pFMrrd7tsSffs+cPGtXqxZHVy6FmhIlptwxN5gnfEtgv1uF0W5KvI9W20X//cOsmVBjtrg13MfTl31xG1FFwaVx3cpFTq0PSp4+B81CQ1Tk5s1UCcPzhAWYQr996Mf4uKzD5/Mewr+zelDpJWfI8dsHah1zujHjIrPPIiHHDtGVzNyaZijn9uFbrj5elFauUoPzvwxthlDT8q+jWwqdFwgzycg0bNdZNcHqmfcJK5i4Eg/gMmepDym772Cxo8jno7b8Ic+itiexATQFv2YpKWB6HTLdgFSPg2O57egDaIObJXpuDGh3NqeqjE+AOJw0+a1O5AVKlpMkXniXvBuLO9snSJIT5bln1sY5ZJqkf1e4OwfTOBHKj1Fjy47psyElZVRk7Rk4zgRlNoVMYUiXZMjFr1UIbtvIuLTF5w/FdnS7IBrfhahSZF2uvGX131NTdRVauj7vDcIgaC9VFkxmbTsgKCob6JmaHNrj4YNL8EdGDd16mbf/H4I/F2KF6Zw2mmHXh/pR62BYVqqzdEGblY3JmDO7Eukqy9jhgPqNfaaB8nPIS6aa2pHj+s/FOnlb+hQyGzPUWlJhnkQ2Yn+zNFMqVsir/nDetszqTjiL84Yl++tj52+s=}
provider:
  win: azure
conda_forge_output_validation: true
